### ISSUE TITLE
[Epic] Login and Registration

### ISSUE THREAD

**Issue by austin-liminal** [limlabs/saleor-storefront-starter#126]
### Description

We want to be able to let users:

- Create a new account using Saleor's built-in email/password authentication
- Log into their existing account

### Dependencies

None

### Links

- [Saleor Auth documentation](https://docs.saleor.io/docs/3.x/api-usage/authentication)
- [Figma prototype](https://www.figma.com/file/6RyYLI5k1zETO9tnsNtATV/Saleor-Template?type=design&node-id=16-602&mode=dev)

### Tasks

- [ ] Add new page skeleton
- [ ] Integrate Login Form with Saleor
- [ ] Integrate Registration Form with Saleor

### Acceptance Criteria

- New users are able to complete the registration
- Existing users are able to login to the app

### Additional Notes/Considerations

Out of scope in this story, but will need to be implemented later:

- Logout
- Reset password
