### ISSUE TITLE
[SEC] Security

### ISSUE THREAD

**Issue by austin-liminal** [limlabs/saleor-storefront-starter#152]
### Epic Name

Security Improvements

### Description

We want to make sure the starter kit is secure and resilient to any known security vectors, including supply chain, command injection, and more.

### Links

- https://blog.logrocket.com/protecting-next-js-apps-csrf-attacks/

### Tasks

- [ ] [SEC] Fix NPM Audit issues
- [ ] [SEC] Set up Dependabot
- [ ] [SEC] CSRF Audit 

### Acceptance Criteria

- All medium or above severity security vulnerabilities reported by NPM to this point are resolved
- Dependabot is configured to open pull requests when new vulnerabilities are discovered in dependencies
- The app has been inspected for CSRF vulnerabilities with documentation of approach and negative test results
