### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by austin-liminal** [limlabs/saleor-storefront-starter#52]
# Summary

We want users to be able to register and log into Saleor-powered websites...

- to simplify the shopping experience for new and returning visitors
- to increase user retention and LTV for eCommerce customers
- to automatically leverage existing info, such as stored payment info or addresses
- to provide a clear notion of identity for martech, analytics, and privacy usages of personally identifiable information in the Next app

### Customer-facing

- Email/Password Signup
- Login
- Reset Password
- 2FA enrollment (?)
- Verify email address
- Manage stored payment info
- Manage addresses
- Order History

### Developer-facing

- `useIdentity` hook w/ pluggable interface and two out-of-the-box implementations
   - OAuth2
   - Email/Password
- RSC-compatible page and layout boilerplate

## Todos

- [ ] Visual concepts (UX)
- [ ] Technical design doc (Core maintainers)
- [ ] Reusable identity abstraction (Core maintainers)
- [ ] Page implementations (Core maintainers or community)
- [ ] Training (Liminal media team)

**Comment by kyle-liminal** [comment]
rewriting this issue
